"""booking_correct

Revision ID: d432d43ed452
Revises: 7d67665981bb
Create Date: 2025-12-31 10:38:58.407366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd432d43ed452'
down_revision: Union[str, Sequence[str], None] = '7d67665981bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('place_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('person_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('person_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('place_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
